# Generated by Django 4.1.1 on 2022-09-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile/', verbose_name='프로필 이미지'),
        ),
    ]
