# Generated by Django 4.1.1 on 2022-09-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, verbose_name='카테고리')),
                ('description', models.TextField(verbose_name='작품 설명')),
                ('price', models.IntegerField(verbose_name='작품 가격')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('image', models.ImageField(upload_to='', verbose_name='일러스트')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
