# Generated by Django 4.1.1 on 2022-09-10 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='일러스트')),
                ('category', models.CharField(max_length=128, verbose_name='카테고리')),
                ('description', models.TextField(verbose_name='작품 설명')),
                ('purchase_number', models.IntegerField(verbose_name='구매수')),
                ('price', models.IntegerField(verbose_name='작품 가격')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 날짜')),
                ('illustrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_illustrates', to=settings.AUTH_USER_MODEL, verbose_name='작가')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_illustrates', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='작가 프로필')),
            ],
        ),
    ]
