# Generated by Django 4.1.1 on 2022-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illustrates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustrates',
            name='title',
            field=models.CharField(default='illust', max_length=128, verbose_name='작품명'),
            preserve_default=False,
        ),
    ]
